"""Build docs/results.md and docs/decisions.md from their sources. Never edit those two files by hand.

Run from track_2a/:

    python3 scripts/build_docs.py          # rewrite docs/results.md and docs/decisions.md
    python3 scripts/build_docs.py --check  # exit 1 if either is out of date or a run.json is wrong

Sources (one file per entry, so two people adding entries never touch the same file):

- docs/runs/<run>/run.json   one per run: who, when, which code and variant, the numbers.
                             Fields are described in docs/runs/README.md.
- docs/runs/<run>/NOTES.md   what happened in the run (several runs may share one file).
- docs/decisions/<YYYY-MM-DD-HHMM>_<person>_<topic>.md   one per stage or session; the file
                             name sorts them in time.

Checks: every run.json has the required fields, its notes file exists, and where the run's
official_score.json, predictions.jsonl and raw_answers.jsonl exist, run.json's Macro-F1,
per-label F1, evidence score, token and time means, failed calls and unparseable answers
equal what those files give. So a mistyped number fails.

After a merge conflict in docs/results.md or docs/decisions.md, do not resolve it by hand:
run this script and commit what it writes.
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src import evaluate  # noqa: E402

DOCS = ROOT / "docs"
RUNS = DOCS / "runs"
DECISIONS = DOCS / "decisions"

REQUIRED = ("person", "date", "start_utc", "kind", "code", "task", "cases", "setup", "format",
            "model", "endpoint", "notes", "results")
KINDS = ("model run", "re-parse", "re-score", "offline check", "stopped", "part of another run")
TABLE_KINDS = ("model run", "re-parse", "re-score")
# Every task B run also states these (the "task_b" block of run.json); the task B table shows them.
TASK_B_FIELDS = ("prompt_version", "change", "n_cases", "strict_json", "max_tokens")
NOT_RECORDED = "not recorded"
GENERATED = "<!-- Generated by scripts/build_docs.py from {src}. Do not edit by hand; run the script. -->"

RESULTS_INTRO = """# Results

One row per run. Every number comes from an actual run; each run's
predictions, raw answers and scores are in `docs/runs/`. Dev = the 300 dev
rows (`data/splits.json`). Test has not been run.

Since the contract-alignment stage, the official scorer is the starter's
`evaluate.py` (commit `559b598`), run unchanged. Its minimum Macro-F1 for a
valid submission is 0.75 on task B and 0.60 on task A.

Rows are sorted by date and start time (UTC). Each run's folder holds its
`run.json` (who ran it, which code and settings, the numbers) and its notes;
the notes of all runs follow below the tables. Per-label F1 is shown as E/N/C.
"""

OFFLINE_INTRO = """## Offline retrieval checks (no model calls)

`scripts/retrieval_check.py` on the 201 dev task A cases with a gold passage
(labels 0 and 2), booklets from `scripts/fetch_dev_booklets.py`. No tokens are
used; these numbers say how much of the gold passage reaches the model, not
how well it labels. Matching re-implements the starter's normalisation
(partial ratio >= 90), so it approximates the official evidence check.

hit@k: a selected chunk lies inside the gold passage. Evidence ceiling: a
selected page (or, for the full document, any page) would pass the evidence
check, the best evidence score a model could reach by citing it.
"""

DECISIONS_INTRO = """# Decisions

One line per decision, with the reason. Newest stage at the bottom.

Each stage or session is one file in `docs/decisions/`, named
`<YYYY-MM-DD-HHMM>_<person>_<topic>.md` (UTC start time); this page puts them
together in that order.
"""


# ---------------------------------------------------------------- loading

def load_runs():
    """{run id: run.json content}; the run id is the folder path below docs/runs/."""
    runs = {}
    for path in sorted(RUNS.rglob("run.json")):
        runs[path.parent.relative_to(RUNS).as_posix()] = json.loads(path.read_text(encoding="utf-8"))
    return runs


def sort_key(item):
    run_id, run = item
    return (run["date"], run["start_utc"] or "", run_id)  # an unknown start time sorts first


# ---------------------------------------------------------------- checks

def check_run(run_id, run, run_ids):
    """Return a list of problems with one run.json (empty if it is fine)."""
    problems = [f"{run_id}: missing field {f!r}" for f in REQUIRED if f not in run]
    if problems:
        return problems
    folder = RUNS / run_id
    if run["kind"] not in KINDS:
        problems.append(f"{run_id}: kind {run['kind']!r} is not one of {KINDS}")
    if not (folder / run["notes"]).is_file():
        problems.append(f"{run_id}: notes file {run['notes']} not found")
    if run.get("paired_with") and run["paired_with"] not in run_ids:
        problems.append(f"{run_id}: paired_with {run['paired_with']!r} is not a run")
    if run["task"] == "B":
        block = run.get("task_b") or {}
        problems += [f"{run_id}: task_b block lacks {f!r}" for f in TASK_B_FIELDS if f not in block]
        pred_file = folder / "predictions.jsonl"
        if isinstance(block.get("n_cases"), int) and pred_file.is_file():
            n = sum(1 for p in evaluate.load_jsonl(pred_file) if p["id"].endswith("-B"))
            if n != block["n_cases"]:
                problems.append(f"{run_id}: n_cases is {block['n_cases']} in run.json but {n} in predictions.jsonl")
    results = run["results"]
    if run["kind"] in TABLE_KINDS and not results:
        problems.append(f"{run_id}: a {run['kind']} needs results")
    if run["kind"] in TABLE_KINDS and results:
        problems += check_against_files(run_id, run, folder)
    return problems


def check_against_files(run_id, run, folder):
    """Compare run.json's numbers with the run's official_score.json and predictions.jsonl."""
    problems, r, task = [], run["results"], run["task"]
    score_file = folder / "official_score.json"
    if score_file.is_file():
        official = json.loads(score_file.read_text(encoding="utf-8"))["tasks"][task]
        expected = {"macro_f1": official["macro_f1"]}
        expected.update({f"f1 {k}": v["f1"] for k, v in official["per_class"].items()})
        got = {"macro_f1": r["macro_f1"]}
        got.update({f"f1 {k}": v for k, v in r.get("f1", {}).items()})
        if task == "A":
            expected.update({"evidence score": official["evidence_score"],
                             "evidence found": official["evidence"]["found"],
                             "evidence cases": official["evidence"]["cases"]})
            ev = r.get("evidence") or {}
            got.update({"evidence score": ev.get("score"), "evidence found": ev.get("found"),
                        "evidence cases": ev.get("cases")})
        for key, value in expected.items():
            if key in got and not same(got[key], value, 3):
                problems.append(f"{run_id}: {key} is {got[key]} in run.json but {value:.4f} in official_score.json")
    pred_file = folder / "predictions.jsonl"
    if pred_file.is_file() and score_file.is_file():
        preds = [p for p in evaluate.load_jsonl(pred_file) if p["id"].endswith(f"-{task}")]
        cost = evaluate.cost_scores(preds)
        for key, value in (("mean_input_tokens", cost["input_tokens_mean"]), ("mean_time_ms", cost["time_ms_mean"]),
                           ("p95_time_ms", cost["time_ms_p95"])):
            if not same(r[key], value, 0):
                problems.append(f"{run_id}: {key} is {r[key]} in run.json but {value:.1f} in predictions.jsonl")
    raw_file = folder / "raw_answers.jsonl"
    if raw_file.is_file() and run["kind"] == "model run":
        raws = [r_ for r_ in evaluate.load_jsonl(raw_file) if r_["id"].endswith(f"-{task}")]
        for key, count in (("failed_calls", sum(1 for x in raws if x.get("error"))),
                           ("parse_failures", sum(1 for x in raws if x.get("parse_reason")))):
            if r[key] != count:
                problems.append(f"{run_id}: {key} is {r[key]} in run.json but {count} in raw_answers.jsonl")
    return problems


def same(a, b, digits):
    return a is not None and round(float(b), digits) == round(float(a), digits)


# ---------------------------------------------------------------- rendering

def fmt_f1(r, bold):
    text = f"{r['macro_f1']:.3f}"
    if bold:
        text = f"**{text}**"
    if r.get("f1"):
        f = r["f1"]
        text += f" (E {f['entailment']:.3f}, N {f['neutral']:.3f}, C {f['contradiction']:.3f})"
    return text


def fmt_evidence(run):
    ev = run["results"].get("evidence")
    if run["task"] == "B":
        return "not scored for task B"
    if not ev:
        return "–"
    return f"{ev['score']:.3f} ({ev['found']}/{ev['cases']})"


def link(run_id):
    return f"[`{run_id}`](runs/{run_id}/)"


def results_md(runs):
    ordered = sorted(runs.items(), key=sort_key)
    table = [(i, r) for i, r in ordered if r["kind"] in TABLE_KINDS]
    other = [(i, r) for i, r in ordered if r["kind"] in ("stopped", "part of another run")]
    offline = [(i, r) for i, r in ordered if r["kind"] == "offline check" and "hit_at_k" in (r["results"] or {})]
    analyses = [(i, r) for i, r in ordered if r["kind"] == "offline check" and "hit_at_k" not in (r["results"] or {})]

    out = [GENERATED.format(src="docs/runs/*/run.json and NOTES.md"), "", RESULTS_INTRO,
           "## Model runs", "",
           "| Date | Start (UTC) | Person | Run | Code | Format | Task | Cases | Model / endpoint | Setup "
           "| Macro-F1 | Evidence | Parse failures | Failed calls | Mean input tokens | Mean time (ms) | p95 time (ms) |",
           "|" + "---|" * 17]
    for run_id, run in table:
        r = run["results"]
        paired = f"; paired with `{run['paired_with']}`" if run.get("paired_with") else ""
        out.append(f"| {run['date']} | {run['start_utc']} | {run['person']} | {link(run_id)} | {run['code']} "
                   f"| {run['format']}{paired} | {run['task']} | {run['cases']} | {run['model']} / {run['endpoint']} "
                   f"| {run['setup']} | {fmt_f1(r, run.get('highlight'))} | {fmt_evidence(run)} "
                   f"| {r['parse_failures']} | {r['failed_calls']} | {r['mean_input_tokens']} "
                   f"| {r['mean_time_ms']} | {r['p95_time_ms']} |")

    out += ["", "## Task B runs", "",
            "Every task B run, stopped ones included, with what its prompt changed against the previous version. "
            "\"Strict JSON\" means the endpoint was asked to enforce a JSON format (`response_format`). "
            "Times include failed calls; \"not recorded\" means the run kept no record of it.", "",
            "| Date | Start (UTC) | Run | Prompt version | Change against the previous version | Cases | Strict JSON "
            "| max_tokens | Macro-F1 | Failed calls | Mean input tokens | Mean time (ms) | p95 time (ms) |",
            "|" + "---|" * 13]
    for run_id, run in [(i, r) for i, r in ordered if r["task"] == "B"]:
        b, r = run.get("task_b") or {}, run["results"] or {}
        cell = lambda d, k: NOT_RECORDED if d.get(k) is None else d[k]  # noqa: E731
        cases = f"{b['n_cases']} (stopped)" if run["kind"] == "stopped" else cell(b, "n_cases")
        f1 = fmt_f1(r, run.get("highlight")) if r.get("macro_f1") is not None else NOT_RECORDED
        out.append(f"| {run['date']} | {run['start_utc']} | {link(run_id)} | {cell(b, 'prompt_version')} "
                   f"| {cell(b, 'change')} | {cases} | {cell(b, 'strict_json')} | {cell(b, 'max_tokens')} | {f1} "
                   f"| {cell(r, 'failed_calls') if r else cell(b, 'failed_calls')} | {cell(r, 'mean_input_tokens')} "
                   f"| {cell(r, 'mean_time_ms')} | {cell(r, 'p95_time_ms')} |")

    out += ["", "## Stopped runs and parts of other runs (no row of their own)", ""]
    for run_id, run in other:
        extra = f", part of `{run['part_of']}`" if run.get("part_of") else ""
        out.append(f"- {link(run_id)}: {run['kind']}{extra}; {run['date']} {run['start_utc']} UTC, {run['person']}; "
                   f"task {run['task']}, {run['cases']}; {run['setup']}.")

    out += ["", OFFLINE_INTRO,
            "| Date | Start (UTC) | Person | Run | Code | Context | hit@k | Evidence ceiling, selected pages "
            "| Evidence ceiling, all pages | Mean chars sent (selected / full) |",
            "|" + "---|" * 10]
    for run_id, run in offline:
        r = run["results"]
        hit = f"{r['hit_at_k']:.3f}"
        if "hit_at_k_same_language" in r:
            hit += f" (same language {r['hit_at_k_same_language']:.3f}, cross-language {r['hit_at_k_cross_language']:.3f})"
        out.append(f"| {run['date']} | {run['start_utc'] or '–'} | {run['person']} | {link(run_id)} | {run['code']} "
                   f"| {run['variant']}: {run['setup']} | {hit} | {r['evidence_ceiling_selected']:.3f} "
                   f"| {r['evidence_ceiling_all_pages']:.3f} | {r['mean_chars_selected']:,} / {r['mean_chars_full']:,} |")

    out += ["", "## Other offline analyses (no model calls)", ""]
    for run_id, run in analyses:
        out.append(f"- {link(run_id)}: {run['date']} {run['start_utc'] or ''} UTC, {run['person']}; {run['setup']}. "
                   f"{run.get('summary', '')}".rstrip())

    out += ["", "## Runs by person", ""]
    for person in sorted({r["person"] for r in runs.values()}):
        ids = [f"`{i}`" for i, r in ordered if r["person"] == person]
        out.append(f"- **{person}** ({len(ids)}): " + ", ".join(ids))

    out += ["", "## Notes per run", ""]
    seen = []
    for run_id, run in table + other + offline + analyses:
        notes = (RUNS / run_id / run["notes"]).resolve()
        if notes not in seen:
            seen.append(notes)
            out += [notes.read_text(encoding="utf-8").rstrip(), ""]
    return "\n".join(out).rstrip() + "\n"


def decisions_md():
    out = [GENERATED.format(src="docs/decisions/*.md"), "", DECISIONS_INTRO]
    for path in sorted(DECISIONS.glob("*.md")):
        out += [path.read_text(encoding="utf-8").rstrip(), ""]
    return "\n".join(out).rstrip() + "\n"


def build():
    """Return ({output path: text}, [problems])."""
    runs = load_runs()
    problems = [p for run_id, run in runs.items() for p in check_run(run_id, run, set(runs))]
    return {DOCS / "results.md": results_md(runs), DOCS / "decisions.md": decisions_md()}, problems


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--check", action="store_true", help="only check; exit 1 if anything is out of date or wrong")
    args = p.parse_args()
    files, problems = build()
    for problem in problems:
        print("PROBLEM", problem)
    stale = [path for path, text in files.items() if not path.is_file() or path.read_text(encoding="utf-8") != text]
    if args.check:
        for path in stale:
            print(f"OUT OF DATE {path.relative_to(ROOT)}: run python3 scripts/build_docs.py")
        return 1 if problems or stale else 0
    if problems:
        return 1
    for path in stale:
        path.write_text(files[path], encoding="utf-8")
        print("wrote", path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
