"""Write docs/remaining_errors.md: every wrong answer of a saved section-route run (no model calls).

Run from track_2a/ (booklets from scripts/fetch_dev_booklets.py, e5 model files for long parts):

    EMBED_MODEL_DIR=models/multilingual-e5-small python3 scripts/remaining_errors.py \\
        --run docs/runs/2026-10-08_rashad_section-route-vs-embed_devA300/section-route --out docs/remaining_errors.md

For each case whose label differs from the gold label: the claim, the part it was routed to, the
numbered paragraphs Apertus was sent (rebuilt with the same code as the run: src/ is unchanged since
the run's commit; each rebuilt paragraph's page and length are checked against the run's
raw_answers.jsonl, and the script stops on any difference), the answer, the evidence returned, and
the gold passage. Paragraphs are shown as the prompt showed them (section_route.display).
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src import booklet, nli, parse  # noqa: E402
from src.contexts import section_route  # noqa: E402

NAMES = nli.LABEL_NAMES


def load(path):
    return [json.loads(line) for line in Path(path).read_text(encoding="utf-8").splitlines() if line.strip()]


def fence(text):
    return "```text\n" + text.replace("```", "'''").rstrip() + "\n```"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--run", type=Path, required=True)
    ap.add_argument("--cases", type=Path, default=ROOT / "data" / "dev" / "cases.jsonl")
    ap.add_argument("--expected", type=Path, default=ROOT / "data" / "dev" / "expected-labels.jsonl")
    ap.add_argument("--booklets", type=Path, default=ROOT / "output" / "booklets_dev")
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()
    cases = {c["id"]: c for c in load(args.cases)}
    gold = {g["id"]: g for g in load(args.expected)}
    raws = {r["id"]: r for r in load(args.run / "raw_answers.jsonl")}
    preds = [p for p in load(args.run / "predictions.jsonl") if p["id"].endswith("-A")]
    wrong = [p for p in preds if p["label"] != gold[p["id"]]["label"]]

    run_name = args.run.relative_to(ROOT).as_posix() if args.run.is_absolute() else args.run.as_posix()
    out = ["# Remaining errors of `section-route` (session 6, E5)", "",
           f"Generated by `scripts/remaining_errors.py` from `{run_name}` (no model calls). "
           f"{len(wrong)} of {len(preds)} dev task A answers differ from the gold label. "
           "Gold passage = the dataset's `reference_string` for the row (the starter's `expected-labels.jsonl`).", "",
           "The paragraphs are the ones the prompt `A-v4-section-route` numbered, rebuilt with the run's code "
           "(`src/` unchanged since commit `02ecd5d`); every paragraph's page and length equal what the run "
           "recorded in `raw_answers.jsonl`. They are shown as the model saw them (hyphenated line breaks joined, "
           "whitespace collapsed); the evidence items are the verbatim booklet text.", "",
           "Columns: *Gold reached* = at least one sent paragraph lies inside the gold passage (the starter's "
           "evidence rule applied to the paragraph); *Cut* = the part had more than 8,000 characters, so only the 8 "
           "paragraphs most similar to the claim were sent; *Evidence found* = the returned evidence passes the "
           "starter's rule.", "",
           "| # | Case | Part | Claim language / booklet | Gold | Answer | Cited | Gold reached | Cut | Evidence found |",
           "|---|---|---|---|---|---|---|---|---|---|"]
    sections = []
    for n, pred in enumerate(wrong, start=1):
        case, raw, g = cases[pred["id"]], raws[pred["id"]], gold[pred["id"]]
        pages = parse.load_pages(args.booklets / Path(case["booklet"]["path"]).name)
        routed = section_route.route(pages, case["vote"], case["claim"]["text"])
        if routed is None:
            sys.exit(f"{pred['id']}: not routed now, but the run says {raw.get('route')}")
        part, paragraphs = routed
        recorded = [tuple(x) for x in raw["paragraphs_sent"]]
        rebuilt = [(page, len(text)) for page, text in paragraphs]
        if part != raw["route"] or rebuilt != recorded:
            sys.exit(f"{pred['id']}: rebuilt paragraphs differ from the run's record")
        answer = json.loads(raw["answer"])
        cited = answer.get("paragraphs", [])
        found = any(_matches(item["text"], g["reference"]) for item in pred["evidence"][:5])
        reached = [i for i, (_, text) in enumerate(paragraphs, start=1) if _matches(text, g["reference"])]
        whole = booklet.part_paragraphs(pages, booklet.find_vote(booklet.parse(pages), case["vote"]), part)
        cut = len(whole) != len(paragraphs)
        out.append(f"| {n} | [`{pred['id']}`](#{n}-{pred['id'].lower().replace('.', '')}) | {part} "
                   f"| {case['claim']['language']} / {Path(case['booklet']['path']).stem} "
                   f"| {g['label']} {NAMES[g['label']]} | {pred['label']} {NAMES[pred['label']]} | {cited or '–'} "
                   f"| {'yes ' + str(reached) if reached else 'no'} | {'yes' if cut else 'no'} "
                   f"| {'yes' if found else 'no'} |")
        numbered = "\n".join(f"[{i}] (page {page}) {section_route.display(text)}"
                             for i, (page, text) in enumerate(paragraphs, start=1))
        evidence = "\n\n".join(f"(page {item['page']}) {item['text']}" for item in pred["evidence"]) or "(none)"
        sections += [f"## {n}. {pred['id']}", "",
                     f"- **Vote:** {case['vote']}",
                     f"- **Claim** ({case['claim']['language']}): {case['claim']['text']}",
                     f"- **Booklet:** `{case['booklet']['path']}` ({case['booklet']['language']}), "
                     f"routed part: **{part}**, {len(paragraphs)} paragraphs from pages "
                     f"{sorted({p for p, _ in paragraphs})}"
                     + (f" (cut from {len(whole)} paragraphs to the 8 most similar)" if cut else ""),
                     f"- **Sent paragraphs inside the gold passage:** {reached or 'none'}",
                     f"- **Gold:** {g['label']} ({NAMES[g['label']]}); **answer:** `{raw['answer']}` "
                     f"→ {pred['label']} ({NAMES[pred['label']]}); input tokens {pred['metrics']['input_tokens']}",
                     "", "**Paragraphs sent** (numbered as in the prompt):", "", fence(numbered), "",
                     "**Evidence returned:**", "", fence(evidence), "",
                     "**Gold passage** (`reference_string`):", "", fence(g["reference"]), ""]
    args.out.write_text("\n".join(out + [""] + sections).rstrip() + "\n", encoding="utf-8")
    print(f"{len(wrong)} wrong answers written to {args.out}")


def _matches(text, passage):
    """The starter's evidence rule, re-implemented (scripts/check_evidence.py: norm)."""
    from rapidfuzz import fuzz
    sys.path.insert(0, str(ROOT / "scripts"))
    from check_evidence import norm
    t, p = norm(text), norm(passage)
    return bool(t) and len(t) <= 5000 and fuzz.partial_ratio(t, p) >= 90


if __name__ == "__main__":
    main()
